### ISSUE TITLE
🪄 Enhancement - Add support for i18n

### ISSUE THREAD

**Issue by ArtyomVancyan** [typesnippet/mui-phone-input#14]
### Summary

The package contains static strings that are not translated. Also, changes are required in [react-phone-hooks](https://github.com/typesnippet/react-phone-hooks) for the country names.

 - https://mui.com/material-ui/guides/localization/

**Comment by nouaim** [comment]
can we have country names in Arabic?

**Comment by ArtyomVancyan** [comment]
Yes, @nouaim, you can. Please read the [localization](https://github.com/typesnippet/mui-phone-input?tab=readme-ov-file#localization) section of the README. You should use one of the [supported locales](https://mui.com/material-ui/guides/localization/) of MUI (e.g., `arEG`, `arSA`, or `arSD`).
